# Generated by Django 5.0 on 2023-12-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_date", models.DateField(verbose_name="Дата оплаты")),
                ("money", models.IntegerField(verbose_name="Оплаченная сумма")),
                (
                    "pay_method",
                    models.CharField(
                        choices=[("transfer", "Перевод на счет"), ("cash", "Наличные")],
                        default=("transfer", "Перевод на счет"),
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "pay_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "pay_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.lesson",
                        verbose_name="Оплаченный урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплата",
            },
        ),
    ]
